hydra:
  run:
    dir: results/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

project: artifacts_classification

training:
  epochs: 50
  batch_size: 3
  learning_rate: 1e-4


model:
  classes: 2
  name: efficientnet-b0

check: False
